// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class Testuno {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void Testuno() {
    // Test name: Test uno
    // Step # | name | target | value | comment
    // 1 | open | http://www.ifts20.com.ar/ |  | 
    driver.get("http://www.ifts20.com.ar/");
    // 2 | setWindowSize | 1108x790 |  | 
    driver.manage().window().setSize(new Dimension(1108, 790));
    // 3 | type | id=DNI | 23456544 | 
    driver.findElement(By.id("DNI")).sendKeys("23456544");
    // 4 | type | name=Apellido | Rodo | 
    driver.findElement(By.name("Apellido")).sendKeys("Rodo");
    // 5 | type | name=Nombre | Ricalberto | 
    driver.findElement(By.name("Nombre")).sendKeys("Ricalberto");
    // 6 | type | name=Email | t@hotmail.com | 
    driver.findElement(By.name("Email")).sendKeys("t@hotmail.com");
    // 7 | type | name=Telefono | 23451234 | 
    driver.findElement(By.name("Telefono")).sendKeys("23451234");
    // 8 | click | name=carreras |  | 
    driver.findElement(By.name("carreras")).click();
    // 9 | select | name=carreras | value=2 | 
    {
      WebElement dropdown = driver.findElement(By.name("carreras"));
      dropdown.findElement(By.cssSelector("*[value='2']")).click();
    }
    // 10 | click | name=B1 |  | 
    driver.findElement(By.name("B1")).click();
    // 11 | click | name=renglon1 |  | 
    driver.findElement(By.name("renglon1")).click();
    // 12 | select | name=renglon1 | label=14/03/2019- 19.00- MC INSTOSH ALEXIS | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon1"));
      dropdown.findElement(By.xpath("//option[. = '14/03/2019- 19.00- MC INSTOSH ALEXIS']")).click();
    }
    // 13 | click | css=tr:nth-child(2) option:nth-child(3) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(2) option:nth-child(3)")).click();
    // 14 | click | name=renglon2 |  | 
    driver.findElement(By.name("renglon2")).click();
    // 15 | select | name=renglon2 | label=25/02/2019- 19.00- GARCIA HERMELLO EDGARDO | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon2"));
      dropdown.findElement(By.xpath("//option[. = '25/02/2019- 19.00- GARCIA HERMELLO EDGARDO']")).click();
    }
    // 16 | click | css=tr:nth-child(3) option:nth-child(2) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(3) option:nth-child(2)")).click();
    // 17 | click | name=renglon3 |  | 
    driver.findElement(By.name("renglon3")).click();
    // 18 | select | name=renglon3 | label=06/03/2019- 19.00- BARANI SEBASTIAN | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon3"));
      dropdown.findElement(By.xpath("//option[. = '06/03/2019- 19.00- BARANI SEBASTIAN']")).click();
    }
    // 19 | click | css=tr:nth-child(4) option:nth-child(2) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(4) option:nth-child(2)")).click();
    // 20 | click | name=renglon4 |  | 
    driver.findElement(By.name("renglon4")).click();
    // 21 | select | name=renglon4 | label=11/03/2019- 19.00- CAPELLO ALEJANDRA | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon4"));
      dropdown.findElement(By.xpath("//option[. = '11/03/2019- 19.00- CAPELLO ALEJANDRA']")).click();
    }
    // 22 | click | css=tr:nth-child(5) option:nth-child(3) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(5) option:nth-child(3)")).click();
    // 23 | click | name=renglon5 |  | 
    driver.findElement(By.name("renglon5")).click();
    // 24 | select | name=renglon5 | label=28/02/2019- 19.00- PILLON FERNANDO | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon5"));
      dropdown.findElement(By.xpath("//option[. = '28/02/2019- 19.00- PILLON FERNANDO']")).click();
    }
    // 25 | click | css=tr:nth-child(6) option:nth-child(2) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(6) option:nth-child(2)")).click();
    // 26 | click | name=renglon6 |  | 
    driver.findElement(By.name("renglon6")).click();
    // 27 | select | name=renglon6 | label=13/03/2019- 19.00- MC INSTOSH ALEXIS | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon6"));
      dropdown.findElement(By.xpath("//option[. = '13/03/2019- 19.00- MC INSTOSH ALEXIS']")).click();
    }
    // 28 | click | css=tr:nth-child(7) option:nth-child(3) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(7) option:nth-child(3)")).click();
    // 29 | click | name=renglon6 |  | 
    driver.findElement(By.name("renglon6")).click();
    // 30 | select | name=renglon6 | label=27/02/2019- 19.00- MC INSTOSH ALEXIS | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon6"));
      dropdown.findElement(By.xpath("//option[. = '27/02/2019- 19.00- MC INSTOSH ALEXIS']")).click();
    }
    // 31 | click | css=tr:nth-child(7) option:nth-child(2) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(7) option:nth-child(2)")).click();
    // 32 | click | name=renglon7 |  | 
    driver.findElement(By.name("renglon7")).click();
    // 33 | select | name=renglon7 | label=26/02/2019- 19.00- BERTANI JORGE | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon7"));
      dropdown.findElement(By.xpath("//option[. = '26/02/2019- 19.00- BERTANI JORGE']")).click();
    }
    // 34 | click | css=tr:nth-child(8) option:nth-child(2) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(8) option:nth-child(2)")).click();
    // 35 | click | name=renglon8 |  | 
    driver.findElement(By.name("renglon8")).click();
    // 36 | select | name=renglon8 | label=06/03/2019- 19.00- GARCIA HERMELLO EDGARDO | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon8"));
      dropdown.findElement(By.xpath("//option[. = '06/03/2019- 19.00- GARCIA HERMELLO EDGARDO']")).click();
    }
    // 37 | click | css=tr:nth-child(10) option:nth-child(2) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(10) option:nth-child(2)")).click();
    // 38 | click | name=renglon8 |  | 
    driver.findElement(By.name("renglon8")).click();
    // 39 | select | name=renglon8 | label=13/03/2019- 19.00- GARCIA HERMELLO EDGARDO | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon8"));
      dropdown.findElement(By.xpath("//option[. = '13/03/2019- 19.00- GARCIA HERMELLO EDGARDO']")).click();
    }
    // 40 | click | css=tr:nth-child(10) option:nth-child(3) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(10) option:nth-child(3)")).click();
    // 41 | click | name=renglon9 |  | 
    driver.findElement(By.name("renglon9")).click();
    // 42 | select | name=renglon9 | label=06/03/2019- 19.00- GARCIA HERMELLO EDGARDO | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon9"));
      dropdown.findElement(By.xpath("//option[. = '06/03/2019- 19.00- GARCIA HERMELLO EDGARDO']")).click();
    }
    // 43 | click | css=tr:nth-child(11) option:nth-child(2) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(11) option:nth-child(2)")).click();
    // 44 | click | name=renglon11 |  | 
    driver.findElement(By.name("renglon11")).click();
    // 45 | select | name=renglon11 | label=26/02/2019- 19.00- BRUNO JUAN | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon11"));
      dropdown.findElement(By.xpath("//option[. = '26/02/2019- 19.00- BRUNO JUAN']")).click();
    }
    // 46 | click | css=tr:nth-child(13) option:nth-child(2) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(13) option:nth-child(2)")).click();
    // 47 | click | name=renglon10 |  | 
    driver.findElement(By.name("renglon10")).click();
    // 48 | select | name=renglon10 | label=27/02/2019- 19.00- BRUNO JUAN | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon10"));
      dropdown.findElement(By.xpath("//option[. = '27/02/2019- 19.00- BRUNO JUAN']")).click();
    }
    // 49 | click | css=tr:nth-child(12) option:nth-child(2) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(12) option:nth-child(2)")).click();
    // 50 | click | name=renglon12 |  | 
    driver.findElement(By.name("renglon12")).click();
    // 51 | select | name=renglon12 | label=12/03/2019- 19.00- PLANES CASTRO | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon12"));
      dropdown.findElement(By.xpath("//option[. = '12/03/2019- 19.00- PLANES CASTRO']")).click();
    }
    // 52 | click | css=tr:nth-child(14) option:nth-child(3) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(14) option:nth-child(3)")).click();
    // 53 | click | name=renglon13 |  | 
    driver.findElement(By.name("renglon13")).click();
    // 54 | select | name=renglon13 | label=28/02/2019- 19.00- BARANI SEBASTIAN | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon13"));
      dropdown.findElement(By.xpath("//option[. = '28/02/2019- 19.00- BARANI SEBASTIAN']")).click();
    }
    // 55 | click | css=tr:nth-child(15) option:nth-child(2) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(15) option:nth-child(2)")).click();
    // 56 | click | name=renglon14 |  | 
    driver.findElement(By.name("renglon14")).click();
    // 57 | select | name=renglon14 | label=11/03/2019- 19.00- GROPPA MARIANO | 
    {
      WebElement dropdown = driver.findElement(By.name("renglon14"));
      dropdown.findElement(By.xpath("//option[. = '11/03/2019- 19.00- GROPPA MARIANO']")).click();
    }
    // 58 | click | css=tr:nth-child(16) option:nth-child(3) |  | 
    driver.findElement(By.cssSelector("tr:nth-child(16) option:nth-child(3)")).click();
    // 59 | click | name=B1 |  | 
    driver.findElement(By.name("B1")).click();
  }
}
